# version: "3.8"

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Shikhadas@69
      MYSQL_DATABASE: tododb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  todo-app:
    build: .
    container_name: todo-app
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Shikhadas@69
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  mysql_data:
networks:
  todo-net:
    driver: bridge